import anthropic
import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime, timedelta

# ── Configuration (set these as Railway environment variables) ──────────────
ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
GMAIL_ADDRESS     = os.environ["GMAIL_ADDRESS"]       # your Gmail address
GMAIL_APP_PASSWORD = os.environ["GMAIL_APP_PASSWORD"] # Gmail App Password (not your login password)
RECIPIENT_EMAIL   = os.environ.get("RECIPIENT_EMAIL", GMAIL_ADDRESS)

FAMILY_PROFILE = """
- 3 people: 2 adults and one 8-year-old picky eater
- The child dislikes: strong spices, mixed textures, visible onions/mushrooms, 
  and most seafood
- The child likes: pasta, pizza, tacos, chicken tenders, mild flavours, 
  anything with cheese, simple sides like corn or plain rice
- Adults enjoy a wider variety but prefer simple weeknight meals
- Budget-conscious: no expensive specialty ingredients
- Mix of quick meals (under 30 min) and one or two weekend-style meals
"""

# ────────────────────────────────────────────────────────────────────────────

def generate_meal_plan() -> str:
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    next_monday = datetime.now() + timedelta(days=(7 - datetime.now().weekday()))
    week_label  = next_monday.strftime("%B %d, %Y")

    prompt = f"""
You are a friendly family meal planner. Generate a 7-day dinner meal plan 
for the week of {week_label} for the following family:

{FAMILY_PROFILE}

Format your response EXACTLY like this (use plain text, no markdown):

WEEK OF {week_label}
===================

MONDAY: [Meal Name]
TUESDAY: [Meal Name]
WEDNESDAY: [Meal Name]
THURSDAY: [Meal Name]
FRIDAY: [Meal Name]
SATURDAY: [Meal Name]
SUNDAY: [Meal Name]

---RECIPES---

[For each day, provide:]
[DAY]: [Meal Name]
Prep time: X min | Cook time: X min | Kid-friendly: Yes/Mostly/With modification
Ingredients (serves 3):
- item
- item
Instructions:
1. Step
2. Step
Kid tip: [one sentence on how to make it work for a picky eater]

---SHOPPING LIST---

Produce:
- item

Meat & Seafood:
- item

Dairy & Eggs:
- item

Pantry & Dry Goods:
- item

Frozen:
- item

Other:
- item

---MEAL PREP TIPS---
[2-3 sentences of weekend prep tips to make the week easier]
"""

    message = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=4000,
        messages=[{"role": "user", "content": prompt}]
    )
    return message.content[0].text


def format_html_email(meal_plan_text: str) -> str:
    """Wrap the plain-text meal plan in a clean HTML email."""
    lines = meal_plan_text.split("\n")
    html_lines = []

    for line in lines:
        stripped = line.strip()
        if not stripped:
            html_lines.append("<br>")
        elif stripped.startswith("WEEK OF"):
            html_lines.append(f'<h1 style="color:#2d6a4f;font-family:Georgia,serif;">'
                              f'🍽️ {stripped}</h1>')
        elif stripped.startswith("---") and stripped.endswith("---"):
            section = stripped.strip("-").strip()
            html_lines.append(f'<h2 style="color:#1b4332;border-bottom:2px solid #95d5b2;'
                              f'padding-bottom:4px;font-family:Georgia,serif;">{section}</h2>')
        elif any(stripped.startswith(day + ":") for day in
                 ["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY"]):
            html_lines.append(f'<p style="font-size:16px;font-weight:bold;color:#40916c;">'
                              f'{stripped}</p>')
        elif stripped.startswith("Kid tip:"):
            html_lines.append(f'<p style="background:#d8f3dc;padding:6px 10px;border-radius:6px;'
                              f'font-size:14px;">🧒 {stripped}</p>')
        elif stripped.startswith("-"):
            html_lines.append(f'<li style="margin:2px 0;">{stripped[1:].strip()}</li>')
        elif stripped[0].isdigit() and ". " in stripped:
            html_lines.append(f'<li style="margin:3px 0;">{stripped}</li>')
        else:
            html_lines.append(f'<p style="margin:4px 0;">{stripped}</p>')

    body = "\n".join(html_lines)

    return f"""
    <html><body style="font-family:Arial,sans-serif;max-width:680px;margin:auto;
                       padding:20px;color:#1b2e22;background:#f0faf4;">
      <div style="background:white;border-radius:12px;padding:30px;
                  box-shadow:0 2px 12px rgba(0,0,0,0.08);">
        <p style="color:#52b788;font-size:14px;">
          Your weekly meal plan is ready! Reply to this email with any changes 
          and I'll update it for you.
        </p>
        {body}
        <hr style="margin-top:30px;border:none;border-top:1px solid #d8f3dc;">
        <p style="font-size:12px;color:#888;">
          Generated by your family meal planner · Powered by Claude AI
        </p>
      </div>
    </body></html>
    """


import resend

def send_email(html_content: str, plain_text: str):
    resend.api_key = os.environ["RESEND_API_KEY"]
    next_monday = datetime.now() + timedelta(days=(7 - datetime.now().weekday()))
    subject = f"🍽️ Meal Plan for the Week of {next_monday.strftime('%B %d')}"

    resend.Emails.send({
        "from": "Meal Planner <onboarding@resend.dev>",
        "to": os.environ["RECIPIENT_EMAIL"],
        "subject": subject,
        "html": html_content,
    })
    print(f"✅ Meal plan sent!")

def main():
    print("🥗 Generating meal plan...")
    meal_plan = generate_meal_plan()

    print("📧 Sending email...")
    html = format_html_email(meal_plan)
    send_email(html, meal_plan)


if __name__ == "__main__":
    main()
